name: Cron Test

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "*/5 * * * *"

jobs:
  cron-test:
    runs-on: ubuntu-latest
    steps:
      - name: Print time
        run: |
          echo "Cron test triggered"
          echo "Event name: $GITHUB_EVENT_NAME"
          date -u
