name: Autonomous Job Agent

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  run-agent:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Chromium
        run: python -m playwright install chromium

      - name: Write Google service account file
        run: |
          echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}' > service_account.json

      - name: Run autonomous job agent
        env:
          RUN_MODE: live
          MAX_JOBS: 10
          APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
          APIFY_ACTOR_ID: ${{ secrets.APIFY_ACTOR_ID }}
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          GROQ_MODEL: llama-3.1-8b-instant
          HUNTER_API_KEY: ${{ secrets.HUNTER_API_KEY }}
          GMAIL_SENDER_EMAIL: ${{ secrets.GMAIL_SENDER_EMAIL }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          GOOGLE_SERVICE_ACCOUNT_FILE: service_account.json
          GOOGLE_WORKSHEET_NAME: applied_jobs
          RESUME_PATH: ./Resume_Sharath_SDE.pdf
          SESSION_COOKIES_PATH: ./session_cookies.json
          MANUAL_REVIEW_DIR: ./manual_review
          PLAYWRIGHT_USER_AGENT: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
        run: python -m src.main
